title: Harrison's Blog
logo: /assets/img/profile-pic.png
description: Hi, I'm Harrison — cybersecurity student & tech enthusiast.

  This is my blog! I should have some cool posts here, but for now its a work in progress.
  Check back soon for updates!
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
